services:
  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: recruitment_db
    ports:
      - "5432:5432"

  eureka-server:
    image: eclipse-temurin:17-jdk
    container_name: eureka-server
    ports:
      - "8761:8761"
    # Note: Dans un vrai scénario, on builderait les jars d'abord

  api-gateway:
    image: eclipse-temurin:17-jdk
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  auth-service:
    image: eclipse-temurin:17-jdk
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/recruitment_db
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
