import type { Contest, Application, User } from '@/types';

export const mockContests: Contest[] = [
  {
    id: '1',
    title: 'Concours Administrateur Systèmes',
    description: 'Recrutement d\'administrateurs systèmes pour le Ministère de la Technologie. Les candidats doivent avoir une solide expérience en gestion de serveurs Linux, virtualisation, et sécurité informatique. Ce poste offre une excellente opportunité de carrière dans la fonction publique avec des avantages sociaux complets.',
    category: 'Informatique',
    startDate: '2024-01-15',
    endDate: '2024-03-15',
    status: 'OPEN',
    requirements: [
      'Diplôme Bac+3 minimum en informatique',
      'Expérience de 2 ans minimum',
      'Maîtrise de Linux et Windows Server',
      'Connaissance des réseaux TCP/IP',
      'Certifications appréciées (RHCE, AWS)',
    ],
    location: 'Casablanca',
    positions: 5,
    createdAt: '2024-01-01',
  },
  {
    id: '2',
    title: 'Concours Ingénieur DevOps',
    description: 'Le Ministère des Finances recherche des ingénieurs DevOps pour moderniser son infrastructure. Vous serez responsable de l\'automatisation des déploiements, de la gestion des conteneurs, et de l\'optimisation des pipelines CI/CD.',
    category: 'Informatique',
    startDate: '2024-02-01',
    endDate: '2024-04-01',
    status: 'OPEN',
    requirements: [
      'Diplôme d\'ingénieur en informatique',
      'Expérience avec Docker et Kubernetes',
      'Maîtrise de GitLab CI ou Jenkins',
      'Connaissance du cloud (AWS, Azure, GCP)',
      'Scripting (Bash, Python)',
    ],
    location: 'Rabat',
    positions: 3,
    createdAt: '2024-01-10',
  },
  {
    id: '3',
    title: 'Concours Professeur de Mathématiques',
    description: 'L\'Académie Régionale de l\'Éducation et de la Formation recrute des professeurs de mathématiques pour les lycées. Ce concours est ouvert aux titulaires d\'une licence en mathématiques ou équivalent.',
    category: 'Éducation',
    startDate: '2024-01-20',
    endDate: '2024-02-28',
    status: 'OPEN',
    requirements: [
      'Licence en mathématiques minimum',
      'Certificat de qualification pédagogique',
      'Excellentes capacités de communication',
      'Maîtrise du français et de l\'arabe',
    ],
    location: 'Fès',
    positions: 15,
    createdAt: '2024-01-05',
  },
  {
    id: '4',
    title: 'Concours Médecin de Santé Publique',
    description: 'Le Ministère de la Santé organise un concours pour recruter des médecins spécialistes en santé publique. Les candidats rejoindront les équipes régionales de santé pour contribuer aux programmes de prévention.',
    category: 'Santé',
    startDate: '2024-03-01',
    endDate: '2024-05-01',
    status: 'UPCOMING',
    requirements: [
      'Doctorat en médecine',
      'Spécialisation en santé publique',
      'Expérience hospitalière de 3 ans',
      'Capacité à travailler en équipe',
    ],
    location: 'Marrakech',
    positions: 10,
    createdAt: '2024-01-15',
  },
  {
    id: '5',
    title: 'Concours Technicien de Laboratoire',
    description: 'Recrutement de techniciens de laboratoire pour les hôpitaux publics. Les candidats effectueront des analyses médicales et biologiques sous la supervision de biologistes.',
    category: 'Santé',
    startDate: '2024-02-15',
    endDate: '2024-04-15',
    status: 'OPEN',
    requirements: [
      'DUT ou BTS en biologie médicale',
      'Formation aux normes de sécurité',
      'Maîtrise des équipements de laboratoire',
      'Rigueur et précision',
    ],
    location: 'Tanger',
    positions: 8,
    createdAt: '2024-01-12',
  },
  {
    id: '6',
    title: 'Concours Architecte Urbaniste',
    description: 'La Direction de l\'Urbanisme recrute des architectes urbanistes pour participer aux projets d\'aménagement territorial. Vous contribuerez à la planification et au développement durable des villes.',
    category: 'Architecture',
    startDate: '2024-02-20',
    endDate: '2024-04-20',
    status: 'OPEN',
    requirements: [
      'Diplôme d\'architecte DENA ou équivalent',
      'Spécialisation en urbanisme',
      'Maîtrise des logiciels de CAO/DAO',
      'Connaissance des réglementations urbaines',
    ],
    location: 'Agadir',
    positions: 4,
    createdAt: '2024-01-18',
  },
];

export const mockApplications: Application[] = [
  {
    id: '1',
    contestId: '1',
    contestTitle: 'Concours Administrateur Systèmes',
    candidateId: '1',
    candidateName: 'Ahmed Benali',
    candidateEmail: 'ahmed.benali@email.com',
    cvUrl: '/uploads/cv-ahmed.pdf',
    coverLetter: 'Je suis passionné par l\'administration système depuis plus de 5 ans...',
    status: 'PENDING',
    appliedAt: '2024-01-20',
  },
  {
    id: '2',
    contestId: '1',
    contestTitle: 'Concours Administrateur Systèmes',
    candidateId: '2',
    candidateName: 'Fatima Zahra',
    candidateEmail: 'fatima.zahra@email.com',
    cvUrl: '/uploads/cv-fatima.pdf',
    coverLetter: 'Forte d\'une expérience de 3 ans en tant qu\'administratrice système...',
    status: 'ACCEPTED',
    appliedAt: '2024-01-22',
  },
  {
    id: '3',
    contestId: '2',
    contestTitle: 'Concours Ingénieur DevOps',
    candidateId: '1',
    candidateName: 'Ahmed Benali',
    candidateEmail: 'ahmed.benali@email.com',
    cvUrl: '/uploads/cv-ahmed.pdf',
    coverLetter: 'Mon expérience en DevOps m\'a permis de maîtriser Docker et Kubernetes...',
    status: 'REJECTED',
    appliedAt: '2024-02-05',
  },
  {
    id: '4',
    contestId: '5',
    contestTitle: 'Concours Technicien de Laboratoire',
    candidateId: '3',
    candidateName: 'Youssef El Amrani',
    candidateEmail: 'youssef.amrani@email.com',
    cvUrl: '/uploads/cv-youssef.pdf',
    coverLetter: 'Diplômé en biologie médicale, je souhaite contribuer...',
    status: 'PENDING',
    appliedAt: '2024-02-18',
  },
];

export const mockUsers: User[] = [
  {
    id: '1',
    email: 'admin@example.com',
    name: 'Admin User',
    role: 'ADMIN',
    createdAt: '2024-01-01',
  },
  {
    id: '2',
    email: 'candidate@example.com',
    name: 'Candidate User',
    role: 'CANDIDATE',
    createdAt: '2024-01-05',
  },
];

export const categories = [
  'Informatique',
  'Éducation',
  'Santé',
  'Architecture',
  'Finance',
  'Administration',
  'Ingénierie',
];
